### ISSUE TITLE
timestamps getting read in as `Int128`, `INT96` in the schema

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaIO/Parquet.jl#35] opened 2019-07-02 19:20 UTC
I'm seeing this happen to timestamps when reading in a `snappy` compressed parquet.  These show up as normal timestamps (some are DateTime, others are Date) when read in Python using `pyarrow`.

Attempting to look into this now.

**Comment by xiaodaigh** [comment] 2020-05-14 14:45
Hope it's not caused by the arrow schema

**Comment by tanmaykm** [comment] 2020-05-18 06:37
Int96 timestamps were represented as Julia Int128. But with #50 and https://github.com/JuliaIO/Parquet.jl/pull/71/commits/d8c1739153e563f64831e250d5d58555ffcbc37a it should be possible to read them as Julia `DateTime` now.

Closing.

**Closed by tanmaykm** 2020-05-18 06:37 UTC
